// class version 50.0 (50)
// access flags 0x21
public class scala/util/control/Exception$Catch$ {

  // access flags 0x9
  public static INNERCLASS scala/util/control/Exception$Catch$ scala/util/control/Exception Catch$
  // access flags 0x11
  public final INNERCLASS scala/util/control/Exception$Catch$$anonfun$$lessinit$greater$default$3$1 null null

  // access flags 0x19
  public final static Lscala/util/control/Exception$Catch$; MODULE$

  // access flags 0x1
  // signature <T:Ljava/lang/Object;>()Lscala/Option<Lscala/util/control/Exception$Finally;>;
  // declaration: scala.Option<scala.util.control.Exception$Finally> $lessinit$greater$default$2<T>()
  public $lessinit$greater$default$2()Lscala/Option;
    GETSTATIC scala/None$.MODULE$ : Lscala/None$;
    ARETURN
    MAXSTACK = 1
    MAXLOCALS = 1

  // access flags 0x1
  // signature <T:Ljava/lang/Object;>()Lscala/Function1<Ljava/lang/Throwable;Ljava/lang/Object;>;
  // declaration: scala.Function1<java.lang.Throwable, java.lang.Object> $lessinit$greater$default$3<T>()
  public $lessinit$greater$default$3()Lscala/Function1;
    NEW scala/util/control/Exception$Catch$$anonfun$$lessinit$greater$default$3$1
    DUP
    INVOKESPECIAL scala/util/control/Exception$Catch$$anonfun$$lessinit$greater$default$3$1.<init> ()V
    ARETURN
    MAXSTACK = 2
    MAXLOCALS = 1

  // access flags 0x9
  public static <clinit>()V
    NEW scala/util/control/Exception$Catch$
    INVOKESPECIAL scala/util/control/Exception$Catch$.<init> ()V
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 0

  // access flags 0x1
  public <init>()V
    ALOAD 0
    INVOKESPECIAL java/lang/Object.<init> ()V
    ALOAD 0
    PUTSTATIC scala/util/control/Exception$Catch$.MODULE$ : Lscala/util/control/Exception$Catch$;
    RETURN
    MAXSTACK = 1
    MAXLOCALS = 1
}
